# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: yoe

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - bash -c './scripts/extract-changelog.sh $(git describe --tags --abbrev=0) > .release-notes.md'

builds:
  - main: ./cmd/yoe
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - arm64
      - amd64
      - riscv64
    ignore:
      - goos: darwin
        goarch: riscv64

archives:
  - formats: ['binary']
    name_template: >-
      {{ .ProjectName }}-
      {{- title .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    To update, run: `yoe update`

    Or download the binary for your architecture and place it in your PATH.

    **Note:** Yoe is in heavy development. We recommend cleaning your build
    directory and re-creating projects (`yoe init`) with each new release.
