package starlark

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"go.starlark.net/starlark"
)

const localStarFile = "local.star"

// LocalOverrides holds values loaded from <project-dir>/local.star.
// Empty fields mean the file did not specify that value (or did not exist).
type LocalOverrides struct {
	Machine    string
	DeployHost string // last-used target for `yoe deploy` from the TUI
	Query      string // last-saved TUI search query (in:base-image, etc.)
}

// LoadLocalOverrides reads <projectDir>/local.star if it exists and
// returns any overrides declared via local(...). Returns a zero-value
// struct (and nil error) when the file is absent.
func LoadLocalOverrides(projectDir string) (LocalOverrides, error) {
	path := filepath.Join(projectDir, localStarFile)
	if _, err := os.Stat(path); os.IsNotExist(err) {
		return LocalOverrides{}, nil
	} else if err != nil {
		return LocalOverrides{}, fmt.Errorf("stat %s: %w", path, err)
	}

	var captured LocalOverrides
	localFn := starlark.NewBuiltin("local", func(thread *starlark.Thread, _ *starlark.Builtin, _ starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
		for _, kv := range kwargs {
			key, ok := kv[0].(starlark.String)
			if !ok {
				continue
			}
			v, ok := kv[1].(starlark.String)
			if !ok {
				return nil, fmt.Errorf("local: %s must be a string", string(key))
			}
			switch string(key) {
			case "machine":
				captured.Machine = string(v)
			case "deploy_host":
				captured.DeployHost = string(v)
			case "query":
				captured.Query = string(v)
			default:
				return nil, fmt.Errorf("local: unknown keyword %q", string(key))
			}
		}
		return starlark.None, nil
	})

	thread := &starlark.Thread{Name: "local"}
	predeclared := starlark.StringDict{"local": localFn}
	if _, err := starlark.ExecFile(thread, path, nil, predeclared); err != nil {
		return LocalOverrides{}, fmt.Errorf("evaluate %s: %w", path, err)
	}
	return captured, nil
}

// WriteLocalOverrides writes the given overrides to <projectDir>/local.star,
// overwriting the file. Always emits the standard auto-generated header.
// Empty fields are omitted so the file stays small and explicit.
func WriteLocalOverrides(projectDir string, ov LocalOverrides) error {
	path := filepath.Join(projectDir, localStarFile)
	var b strings.Builder
	b.WriteString("# local.star — generated by yoe; safe to delete or hand-edit.\n")
	b.WriteString("# Per-developer overrides for this project. Not checked in.\n\n")
	b.WriteString("local(\n")
	if ov.Machine != "" {
		fmt.Fprintf(&b, "    machine = %q,\n", ov.Machine)
	}
	if ov.DeployHost != "" {
		fmt.Fprintf(&b, "    deploy_host = %q,\n", ov.DeployHost)
	}
	if ov.Query != "" {
		fmt.Fprintf(&b, "    query = %q,\n", ov.Query)
	}
	b.WriteString(")\n")
	return os.WriteFile(path, []byte(b.String()), 0o644)
}
